server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crystarium_db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}